### ISSUE TITLE
Trailing dot leads to no result in checkZone

### ISSUE THREAD

**Issue by panzerdev** [libdns/autodns#4]
When using caddy the zone provided is for example `foo.com.` with a trailing comma. The Autodns API doesn't deliver results based on that zone in the checkZone function.

My solution suggestion

https://github.com/libdns/autodns/commit/8354be6cfbc0eec473480cd92c156ea170a63996

**Comment by till** [comment]
Please send a PR

**Comment by till** [comment]
@panzerdev Thank you so much! :)
